bitacora/urls.py
from django.conf.urls import patterns, include, url
from bitacora.views import *
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',
    # Examples:
    #url(r'^notas/', 'bitacora.views.home', name='home'),
   # url(r'^notas/', index.as_view(), name='home'),
    
	#url(r'api-auth/'), include('rest_framework.urls',namespace='rest_framework')),
    #CATEGORIA
    url(r'^notas/$', login_required(ListarNotas.as_view()), name='list_notas'),
    url(r'^notas/por-categoria/(\d+)/$',  login_required(FiltrarNotas_x_Categoria.as_view()), name='filter_notas'),
    url(r'^notas/(\d+)/$',  login_required(DetalleNota.as_view()), name='detail_nota'),
    url(r'^notas/nueva/$',  login_required(NuevaNota.as_view()), name='new_nota'),
    url(r'^notas/busqueda/$',  login_required(BusquedaAvanzada.as_view()), name='search_notas'),
    url(r'^estadisticas/$', Estadistica_Notas.as_view()),
    url(r'^estadisticas/usuario$', Estadistica_NotasXUsuario.as_view()),
    url(r'^estadisticas/sistemas$', Estadistica_Sistemas.as_view()),
    url(r'^([-\w]+)/$',  login_required(GetTemplate.as_view()), name='template'),
    # url(r'^eaai/', include('eaai.foo.urls')),

)

eaai/urls.py
from django.conf.urls import patterns, include, url
from eaai import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from bitacora.views import CategoryViewSet, UserViewSet
from rest_framework import routers
#from horario.views import saveMachinereboots
router = routers.DefaultRouter()
router.register(r'categorias', CategoryViewSet)
router.register(r'usuarios', UserViewSet)
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'api/', include(router.urls)),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
    	{ 'document_root' : settings.MEDIA_ROOT  }),

    url(r'^bitacora/', include('bitacora.urls')),
    url(r'^sistemas/', include('sistemas.urls')),
    url(r'^dispositivos/', include('dispositivos.urls')),
    
    url(r'^horario/', include('horario.urls')),
    url(r'^gestion/', include('gestion.urls')),

    url(r'^', include('usuario.urls')),
    url(r'^select2/', include('django_select2.urls')),

)

bitacora/models.py
from django.db import models
from django.contrib.auth.models import User
from sistemas.models import *
from .manager import *
# Create your models here.
from django.dispatch import receiver



class Severidad_nota(models.Model):
    name = models.CharField('Nombre',max_length=50,unique=True, )
    description = models.TextField('Descripcion',max_length=120, help_text='Descripcion breve sobre el sistema')
    created_at = models.DateTimeField(auto_now_add=True,verbose_name='creado el')
    updated_at = models.DateTimeField(auto_now=True,verbose_name='actualizado el')
    user = models.ForeignKey(User, 
        verbose_name='Creado por',)

    class Meta:
         #db_table = 'categories'
        ordering = ['created_at']
        verbose_name_plural = 'Niveles de Severidad'
        verbose_name = 'Nivel de Severidad'

    def __unicode__(self):
        return self.name
    
    def creado_por(self):
        return "%s %s" % (self.user.first_name, self.user.last_name,)





class Nota(models.Model):
    severity = models.ForeignKey(Severidad_nota, verbose_name='Estado ',)
    systems = models.ManyToManyField(Sistema, blank=True,verbose_name='Sistemas')
    description = models.TextField(max_length=3000, help_text='Descripcion de la nota',verbose_name='descripcion')
    keywords= models.CharField(max_length=150, help_text='(Opcional) Palabras clave delimitadas por coma',blank=True,)
    referencia = models.ForeignKey('self', verbose_name=u'Referencia a nota', null=True, blank=True,help_text='Campo Opcional')
    adjuntos= models.FileField(upload_to='nota/adjuntos',blank=True,null=True,help_text='Campo Opcional')
    created_at = models.DateTimeField(auto_now_add=True,verbose_name='creado el')
    updated_at = models.DateTimeField(auto_now=True,verbose_name='actualizado el')
    user = models.ForeignKey(User, 
        verbose_name='Creado por',)

    estadisticas=NotasManager()
    objects = models.Manager() # The default manager.

    class Meta:
         #db_table = 'categories'
        ordering = ['-created_at']
        verbose_name_plural = 'Notas'
        verbose_name = 'Nota'

    def __unicode__(self):
        return  "Nota: %d" % (self.pk, )
    
    def creado_por(self):
        return "%s %s" % (self.user.first_name, self.user.last_name,)
        
    def sistemas_involucrados(self):
        return "%d" % (self.systems.count(),)

bitacora/forms.py
from django.forms import ModelForm, TextInput, DateTimeInput
from django.contrib.admin import ModelAdmin
from bitacora.models import  Nota, Severidad_nota
from suit.widgets import EnclosedInput, LinkedSelect
from suit.widgets import EnclosedInput
from suit_redactor.widgets import RedactorWidget
from django_select2.widgets import Select2MultipleWidget, Select2Widget



class NotaForm(ModelForm):
    class Meta:
        model = Nota
        exclude=('user',)
        widgets = {
            'description': RedactorWidget(editor_options={'lang': 'es'}),
            'referencia': Select2Widget(select2_options={
                'minimumResultsForSearch': 1,
                'closeOnSelect': True,
                'width':200
                }),
            'severity': Select2Widget(select2_options={
                'minimumResultsForSearch': 1,
                'closeOnSelect': True,
                'width':200
                })
        }


class EstadoForm(ModelForm):
    class Meta:
        model = Severidad_nota
        exclude=('user',)

class NotaForm2(ModelForm):
    class Meta:
        model = Nota
        exclude=('user',)
        widgets = {
            'keywords': TextInput(attrs={'placeholder': "Palabras clave delimitadas por coma"}),
        }
        

bitacora/views.py
# Create your views here.
from django.views.generic import TemplateView, CreateView, ListView,FormView
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response,get_object_or_404
from django.template.context import RequestContext
from django.template.loader import get_template
from django.core.urlresolvers import reverse_lazy
from bitacora.forms import *
from bitacora.models import *
from sistemas.models import *
from django.contrib.auth.models import User
from .serializers import CategorySerializer, UserSerializer
from rest_framework import viewsets
from django.db.models import Q
import datetime
from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives


#def home(request):
	#return HttpResponse("<h2>HOME</h2>")
#	return render_to_response('index.html', context_instance=RequestContext(request))
class UserViewSet(viewsets.ModelViewSet):
	queryset= User.objects.all()
	serializer_class= UserSerializer

class CategoryViewSet(viewsets.ModelViewSet):
	queryset= Categoria.objects.all()
	serializer_class= CategorySerializer

class GetTemplate(TemplateView):
	def get(self, request,Thetemplate): 
		Thetemplate+=".html"
		return render_to_response('bitacora/'+Thetemplate, locals(),context_instance=RequestContext(request))

class ListarNotas(ListView):
	def get(self, request):
		page_title = 'Bitacora'
		page_sub_title= 'Ultimas 100 notas' 
		template= 'bitacora/notas.html'
		notas= Nota.objects.all()[:100]
		return render_to_response(template, locals(),context_instance=RequestContext(request))

	def post(self,request,*args,**kwargs):
		page_title = 'Bitacora'
		termino=request.POST['search_text']
		page_sub_title= 'Resultados para:  %s' %(termino)
		notas= Nota.objects.filter(Q(keywords__contains=termino) | Q(description__contains=termino)).distinct()[:100] #
		return render_to_response('bitacora/notas.html', locals(),context_instance=RequestContext(request))


class NuevaNota(FormView):
	def get(self, request): 
		page_title = 'Bitacora'
		page_sub_title= 'Agregar nueva anotacion'
		sistemas= Sistema.objects.filter(is_active=True)
		#estados = Severidad_nota.objects.filter(is_active=True)
		form= NotaForm2()
		#notas= Nota.objects.filter(systems_category_name=cat.name)
		return render_to_response('bitacora/nueva.html', locals(),context_instance=RequestContext(request))

	def post(self,request,*args,**kwargs):
		form= NotaForm2(request.POST,request.FILES)
		if form.is_valid():
			nota=form.save(commit=False)
			print nota.description
			nota.user=request.user
			nota.save()
			form.save_m2m()
			#subject, from_email, to = 'Bitacora Electronica', 'from@example.com', 'edxrojas@yahoo.es'
			#text_content = 'This is an important message.'
			#html_content = nota.description
			#msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
			#msg.attach_alternative(html_content, "text/html")
			#msg.send()
			return  HttpResponseRedirect(reverse_lazy('list_notas'))
		else:
			return render_to_response('bitacora/nueva.html', locals(),context_instance=RequestContext(request))


class FiltrarNotas_x_Categoria(TemplateView):
	def get(self, request,idcategoria): 
		page_title = 'Bitacora'
		cat= get_object_or_404(Categoria, pk=idcategoria)
		page_sub_title= 'Notas por categoria:  %s' %(cat.name)
		sistemas= Sistema.objects.filter(category=cat)
		notas= Nota.objects.filter(systems__in=sistemas).distinct()[:100] #
		#notas= Nota.objects.filter(systems_category_name=cat.name)
		return render_to_response('bitacora/notas.html', locals(),context_instance=RequestContext(request))

import os
class DetalleNota(TemplateView):
	def get(self, request,idNota): 
		page_title = 'Bitacora'
		nota= get_object_or_404(Nota, pk=idNota)
		page_sub_title = 'Detalles de nota  %d' %(nota.pk)
		#obtener todos los sistemas que estan en la nota
		sistemas = Sistema.objects.filter(nota__pk=nota.pk)
		#obtener la extension del al archivo adjunto
		if nota.adjuntos:
			filetype = os.path.splitext(nota.adjuntos.__str__())[1]

		return render_to_response('bitacora/detalleNota.html', locals(),context_instance=RequestContext(request))

class BusquedaAvanzada(TemplateView):
	def get(self, request): 
		page_title = 'Bitacora'
		page_sub_title= 'Busqueda especificas'
		return render_to_response('bitacora/busqueda.html', locals(),context_instance=RequestContext(request))

	def post(self,request,*args,**kwargs):
		page_title = 'Bitacora'
		inicio=request.POST['fecha_inicial']
		fin=request.POST['fecha_final']
		termino=request.POST['search_text'].strip()
		page_sub_title= 'Resultados para el rango '+inicio+' - '+ fin
		inicio= inicio+':00-0600'		
		fin= fin+':00-0600'
		if termino and not termino.isspace():
			notas= Nota.objects.filter(created_at__range=[inicio,fin]).filter(Q(keywords__contains=termino) | Q(description__contains=termino)).distinct()[:100]
		else:
			notas= Nota.objects.filter(created_at__range=[inicio,fin]).distinct()[:100]
		
		return render_to_response('bitacora/busqueda.html', locals(),context_instance=RequestContext(request))




import json

class Estadistica_Notas(TemplateView):
    def get(self, request,*args,**kwargs):
    	stats=Nota.estadisticas.status_Count()
    	dataset=[]
    	recordsDict={}
    	for stat in stats:
    		dic={'label':stat.severity.name,'value':stat.total}
    		dataset.append(dic)

    	recordsDict["estadisticas"]=dataset
    	return HttpResponse(json.dumps(dataset,  indent=4),mimetype='application/json') 
        #return HttpResponse(data,mimetype='application/json') 

class Estadistica_Sistemas(TemplateView):
    def get(self, request,*args,**kwargs):
    	stats=Nota.estadisticas.sist_statistics(0)
    	dataset=[]
    	for stat in stats:
    		if stat["total"] > 0:
    			dataset.append(stat)
        return HttpResponse(json.dumps(dataset,  indent=4),mimetype='application/json') 


class Estadistica_NotasXUsuario(TemplateView):
    def get(self, request,*args,**kwargs):
    	stats=Nota.estadisticas.Notas_por_Usuario_Count()
    	dataset=[]
    	for stat in stats:
    		if stat["total"] > 0:
    			dataset.append(stat)
        return HttpResponse(json.dumps(dataset,  indent=4),mimetype='application/json') 

        #return HttpResponse(data,mimetype='application/json') 

templates/bitacora/T1tmpl.html
<div class="mceTmpl">	
	<table id='mitabla' class="table table-bordered">
	  <caption>Estado de radio enlaces</caption>
	  <thead>
	    <tr id="tableHeader">
	      <th width="150px">Emplazamiento</th>
	      <th width="150px">Bit Status</th>
	      <th width="150px">Pag. Radio</th>
	      <th width="150px">Frec. 119.4 A</th>       
	      <th width="150px">Frec. 119.4 B </th> 
	      <th width="150px">Frec. 126.9 A</th> 
	      <th width="150px">Frec. 126.9 B</th>    
	    </tr>
	  </thead>
	  <tbody>
	  	<tr>
	  		<td>La Cuesta</td>
	  		<td>OK</td>
	  		<td>OK </td>
	  		<td>OK</td>
	  		<td>OK</td>
	  		<td>OK</td>
	  		<td>OK</td>
	  	</tr>
	  	<tr>
	  		<td>El Casita</td>
	  		<td>OK</td>
	  		<td>OK </td>
	  		<td>OK</td>
	  		<td>OK</td>
	  		<td>OK</td>
	  		<td>OK</td>
	  </tbody>
	</table>

</div>


{% comment %}

{% endcomment %}

templates/bitacora/Tmp2.html
<p>No se reportan incidencias durante el turno, todo los sistemas y equipos Aircon, Radar y SDC, operando ok, entrego turno a </p>

templates/bitacora/busqueda.html
{% extends "base.html" %}


{% block statics %}
<link rel="stylesheet" href="{{STATIC_URL}}css/jquery-ui.min.css">
	<link rel="stylesheet" href="{{STATIC_URL}}css/jquery.datetimepicker.css">
	<link rel="stylesheet" href="{{STATIC_URL}}css/jquery.flipcountdown.css">

<script src='{{STATIC_URL}}js/vendor/jquery/jquery.js'></script>
<script src='{{STATIC_URL}}js/vendor/jquery-ui.min.js'></script>
<script src='{{STATIC_URL}}js/vendor/jquery.datetimepicker.js'></script>

<!-- JqWidgets styles -->
<link rel="stylesheet" href="{{STATIC_URL}}js/jqwidgets/styles/jqx.base.css">
<link rel="stylesheet" href="{{STATIC_URL}}js/jqwidgets/styles/jqx.bootstrap.css">
<!-- Jqwidget -->
<script src="{{STATIC_URL}}js/jqwidgets/jqxcore.js" type="text/javascript"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/jqwidgets/jqxdatetimeinput.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/jqwidgets/jqxcalendar.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/jqwidgets/jqxtooltip.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/jqwidgets/globalization/globalize.js"></script>

<script>
	$(document).ready(function() {
		$("#fecha_inicial,#fecha_final").jqxDateTimeInput({
			width: '120px', height: '25px'
		});


		$("#id_fecha_inicio").datetimepicker({
	   		lang:'es',
	   		format:'Y-m-d H:i',
	   		startDate:'+1971/01/01',
 			maxDate:'+1970/01/01',//tommorow is maximum date calendar

	    });
	    $("#id_fecha_fin").datetimepicker({
	   		lang:'es',
	   		format:'Y-m-d H:i',
	   		startDate:'+1971/01/01',
	   		maxDate:'+1970/01/01',//tommorow is maximum date calendar
	    });

		$("article").hover(function() {
			$(this).css('box-shadow', '7px 7px 5px #888');
//			$(this).animate({ 'zoom': 1.02 }, 100);
			
		}, function() {
			$(this).css('box-shadow', ' 2px 2px 10px #102648');
//			$(this).animate({ 'zoom': 1 }, 100);
		});

	});
</script>
{% endblock statics %}

{% block left_content %}
<br>
<!-- 
<h5  class="subheader">Categorias</h5 >
		<ul class="side-nav">
		{% for categoria in categorias %}
			<li class="snav text-right">
				<a href="{% url 'filter_notas' categoria.pk %}">
					{{categoria.name}}
				</a>
			</li>
		{% endfor %}
		</ul>
 -->
{% endblock left_content %}


{% block main_content %}


	<dl class="sub-nav ">
		<dt>Opciones:</dt>
			<dd class="sn "><a href="{% url 'list_notas' %}">
				<i class='fi-list-bullet'></i> Todas</a>
			</dd>
			<dd class="sn "><a href="{% url 'new_nota' %}">
				<i class='fi-plus'></i> Crear nota</a>
			</dd>
	</dl>

<div id='fecha_inicial'>
</div>
<div id='fecha_final'>
</div>

<form method="POST">
	{% csrf_token %}
	<div class="row collapse">
		<div class="row collapse ">
			<div class="small-2 medium-1 columns text-right">
	        	<i class='fi-calendar' style='font-size:35px '></i>
	        	&nbsp;
	        </div>
	        <div class="small-3 medium-2 columns">
	          <input type="text" id='id_fecha_inicio' placeholder='Fecha Inicial' name='fecha_inicial' autocomplete="off" required>
	        </div>
	        <div class="small-3 medium-1 columns text-right">
	        	<i class='fi-calendar' style='font-size:35px '></i>
	        	&nbsp;
	        </div>
	        <div class="small-2 medium-2 end columns">
	          <input type="text" id='id_fecha_fin' placeholder='Fecha Final' name='fecha_final' autocomplete="off" required>
	        </div>
	        <div class="small-3 medium-1 columns">
	        	&nbsp;
	        </div>
            <div class="small-2 medium-2 end columns">
		        <button class="button small " data-hint="Seguidos" type="submit">
				  <i class="fi-magnifying-glass"></i> Buscar
				</button>
	        </div>
	    </div>
	    <div class="row">
	    	<div class="small-2 medium-1 columns text-right">
	        	<i class='fi-page-search' style='font-size:30px '></i>
	        </div>
	        <div class="small-3 medium-4 end columns">
	          <input type="text" placeholder='Termino de busqueda (Opcional)' name='search_text'>
	        </div>
	    </div>
  	</div>
</form>



<section>
	{% load tz %}
		<label class='label round success'>Resultados: {{notas.count}}</label>
		{% for  nota in notas %}
			<article id='{{nota.pk}}'>
				<div class="row">
					<div class="medium-2 columns text-center autor">
						<img src="{{MEDIA_URL}}{{nota.user.perfil.foto}}" alt="">
						<label class='small-12 label radius'>{{nota.user.first_name}}</label>
					</div>
					<div class="medium-10 columns nota">
						<div class="clearfix cabecera">
							<label class="left"> {{nota.created_at | date:"D d \d\e F \d\e\l Y " }} | {{nota.created_at | utc |  date:"D d \d\e F \d\e\l Y "}}<br>
								{{nota.created_at | date:"h:i a  (\ e O \)"  }} |
								{{nota.created_at | utc |  date:"h:i a (\ e O \) "  }}
						    </label>
						    <label class="right">{{nota}}</label>
						</div>

						<div class="clearfix cuerpo">
							<label class="left estado{{nota.severity.pk}} radius"> <i class='fi-flag'></i> {{nota.severity.name}} </label><br>
							{{nota.description|safe|truncatewords:20}}
							{% if nota.keywords %}
							<label>
								<i class='fi-pricetag-multiple'></i> {{nota.keywords}}
							</label>
							{% endif %}
							{% if nota.referencia %}
							<label>
								<i class='fi-link'></i> referencia a <a href="#{{nota.referencia.pk}}">{{nota.referencia}}</a>
							</label>
							{% endif %}
						</div>
						<div class="clearfix tags">
							<label class='left'><i class='fi-clock'></i> Hace {{nota.created_at|timesince}}</label>
							<label class="right"><a href="{% url 'detail_nota' nota.pk %}"> <i class='fi-zoom-in'></i> Ver detalles</a></label>
						</div>
					</div>
				</div>
			</article>
		
		{% empty %}
				<h4><i class='fi-trees'></i> No hay elementos que mostrar</h4>
		{% endfor %}			

</section>
{% endblock main_content %}

templates/bitacora/nueva.html
{% extends "base.html" %}
{% block statics %}
	<link rel="stylesheet" href="{{STATIC_URL}}css/select2.css">	

	<script src='{{STATIC_URL}}js/vendor/jquery/jquery.js'></script>
	<script src='{{STATIC_URL}}js/vendor/tinymce/tinymce.min.js'></script>
	<script src='{{STATIC_URL}}js/vendor/select2.min.js'></script>
	<script src='{{STATIC_URL}}js/vendor/select2_locale_es.js'></script>
	<script>
		$(document).ready(function() {
			tinymce.init({
			    selector: "textarea",
			    language : 'es',
			    fontsize_formats: "8pt 9pt 10pt 11pt 12pt ",
			    browser_spellcheck : true ,
			    plugins: "charmap textcolor  link  table  template  print lists",

			    toolbar: "undo redo  forecolor backcolor template styleselect bold italic image alignleft aligncenter alignright bullist numlist fontselect ",
			    templates : [
			        {
			            title: "Entrega de turno",
			            url: "/bitacora/Tmp2",
			            description: "Plantilla para entrega de turno"
			        },
			        {
			            title: "Estado Radio Enlaces",
			            url: "/bitacora/T1tmpl",
			            description: "Estado emplazamientos (No aplicar estilos o clores al contenido de la tabla)"
			        }
			    ]	
			 });


			 $("#id_severity").select2({
			 	  width: "resolve"
			 }); 

			 $("#id_referencia").select2({
			 	  width: "resolve"
			 }); 
			 $("#sistemas_cbox").select2({
			 	  width: "resolve",
			 	  placeholder:"Seleccione los sistemas relacionados a la nota"
			 }); 
			 $("#sistemas_cbox").on("select2-selecting",function(event) {
			 	valor = event.val
			 	$('#id_systems option[value='+valor+']').attr('selected','selected');
			 });


		});
	</script>

{% endblock statics %}


{% block main_content %}
	
	<dl class="sub-nav ">
		<dt>Opciones:</dt>
			<dd class="sn "><a href="{% url 'list_notas' %}">
				<i class='fi-list-bullet'></i> Todas</a>
			</dd>
			<dd class="sn "><a href="{% url 'search_notas' %}">
				<i class='fi-magnifying-glass'></i> Busqueda</a>
			</dd>
	</dl>	


<form method='POST' enctype='multipart/form-data' >
	{% csrf_token %}
	
	{% if form.errors %}				 	
		<audio src="{{MEDIA_URL}}audio/dubstep_alert.mp3" autoplay></audio>
	{% endif %}

	<div class="row">
		<div class="medium-1 columns text-right">{{form.severity.label_tag}}</div>
		<div class="medium-4 columns "> 
			<span data-tooltip class="" title="Indica el grado de incidencia de la nota">
				{{form.severity}}
			</span>
			{% if form.severity.errors %}
				<div data-alert class="alert-box warning radius">
					Es necesario que indique el estado
					 <a href="#" class="close">&times;</a>
				</div>
			{% endif %}
		</div>
		<div class="medium-1 columns text-right">{{form.referencia.label_tag}}</div>
		<div class="medium-4 columns end">
			<span data-tooltip class="has-tip" title="Hace referencia a una anotacion anterior, la cual se relaciona con algo descrito en la nota que estas creando">
				{{form.referencia}} 
			</span>
		</div>	
	</div>
	
	<div class="row">
		<div class="medium-1 columns text-right">{{form.adjuntos.label_tag}}</div>
		<div class="medium-4 columns ">
			<span data-tooltip class="" title="Adjunta un archivo que creas que es realmente necesario, en caso de querer agregar mas de uno, comprimelos en un solo para poder subirlo">
				{{form.adjuntos}} 
			</span>
		</div>
		<div class="medium-1 columns text-right">
			<span data-tooltip class="" title="palabras delimitadas por coma, serviran para realizar busquedas rapidas">
				{{form.keywords.label_tag}}
			</span>		
		</div>
		<div class="medium-4 columns end">	
			{{form.keywords}}
		</div>
	</div>
	<div class="row">
		 <div class="medium-1 columns text-right">{{form.systems.label_tag}}</div>
		<div class="medium-8 columns end">
			<select name="sistemas_cbox" id="sistemas_cbox" multiple>
				{% for sistema in sistemas %}
					<option value="{{sistema.pk}}">{{sistema.short_name}}</option>
				{% endfor %}
			</select>
		</div>
	</div><br>
	<div class="row">
		<div class="medium-1 columns text-right">{{form.description.label_tag}}</div>
		<div class="medium-8 columns ">
			{% if form.description.errors %}
				<div data-alert class="alert-box warning radius">
					Es necesario que especifiques el contenido de la nota
					 <a href="#" class="close">&times;</a>
				</div>
			{% endif %}
			{{form.description}}
		</div>
		<div class="medium-3 columns ">
			<button class="button small " data-hint="Seguidos" type="submit">
			  <i class="fi-save"></i> Guardar
			</button>

		</div>
	</div>

	<select name="systems" id="id_systems" multiple hidden>
				{% for sistema in sistemas %}
					<option value="{{sistema.pk}}">{{sistema.short_name}}</option>
				{% endfor %}
	</select>
</form>


{% endblock main_content %}