eaai/urls.py
from django.conf.urls import patterns, include, url
from eaai import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from bitacora.views import CategoryViewSet, UserViewSet
from rest_framework import routers
#from horario.views import saveMachinereboots
router = routers.DefaultRouter()
router.register(r'categorias', CategoryViewSet)
router.register(r'usuarios', UserViewSet)
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'api/', include(router.urls)),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
    	{ 'document_root' : settings.MEDIA_ROOT  }),

    url(r'^bitacora/', include('bitacora.urls')),
    url(r'^sistemas/', include('sistemas.urls')),
    url(r'^dispositivos/', include('dispositivos.urls')),
    
    url(r'^horario/', include('horario.urls')),
    url(r'^gestion/', include('gestion.urls')),

    url(r'^', include('usuario.urls')),
    url(r'^select2/', include('django_select2.urls')),

)

usuario/urls.py
from django.conf.urls import patterns, include, url
from usuario.views import *
from django.contrib.auth.forms import AdminPasswordChangeForm

urlpatterns = patterns('',
    

    # Examples:
    url(r'^$', 'django.contrib.auth.views.login', {'template_name':'index.html'},name='login'),
    
    url(r'^salir/$', 'django.contrib.auth.views.logout_then_login', name='logout'),
    url(r'^perfil/$', perfil.as_view(), name='perfil'),
    url(r'^perfil/actualizar$', ActualizarPerfil.as_view(), name='actualizar_perfil'),
    url(r'^perfil/cambio-de-clave$', Changepassword.as_view(), name='actualizar_clave'),

   # url(r'^notas/', index.as_view(), name='home'),

 

)

usuario/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
import os

class Perfil(models.Model):
    usuario = models.OneToOneField(User)
    foto = models.ImageField( upload_to='perfiles',null=True, default= 'perfiles/default.jpg')
    cargo= models.CharField(max_length=100, blank=True)
    telefono= models.CharField(max_length=15, blank=True)
    fecha_nacimiento= models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Perfiles'
        verbose_name = 'Perfil'
        
    def __unicode__(self):
        return self.usuario.username 


#esta funcion va fuera de la clase y es para eliminar un archivo cuando se actualiza el campo
@receiver(models.signals.pre_save, sender=Perfil)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """Deletes file from filesystem
        when corresponding `MediaFile` object is changed.
    """
    #si no existe el objeto no hagas nada y salvalo normal
    if not instance.pk:
        return False
    #intenta darme el archivo anterior
    try:
        old_file = Perfil.objects.get(pk=instance.pk).foto
    except Perfil.DoesNotExist:
        return 

    if os.path.basename(old_file.path) == "default.jpg":
        return False
    #dame el archivo q viene en el objeto a actualizar
    new_file = instance.foto
    #si no son los mismos archivos elimina el anterior
    if not old_file == new_file:
        if os.path.isfile(old_file.path):
            os.remove(old_file.path)




User.perfil = property (lambda u: Perfil.objects.get_or_create(usuario=u)[0])

usuario/forms.py
from django.forms import ModelForm
from usuario.models import Perfil

class PerfilForm(ModelForm):
	class Meta:
		model= Perfil
		exclude = ['usuario']

usuario/views.py
# Create your views here.
# Create your views here.
from django.views.generic import TemplateView, CreateView, ListView, FormView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response,get_object_or_404
from django.template.context import RequestContext
from django.template.loader import get_template
from django.core.urlresolvers import reverse_lazy
from usuario.models import Perfil
from usuario.forms import *
from django.contrib.auth.forms import PasswordChangeForm

#def home(request):
    #return HttpResponse("<h2>HOME</h2>")
#   return render_to_response('index.html', context_instance=RequestContext(request))



class perfil(TemplateView):
    @method_decorator(login_required)
    def get(self, request):     
        page_title = 'Perfil'
        page_sub_title= 'Perfil de Usuario'
        return render_to_response('usuario/perfil.html', locals(),context_instance=RequestContext(request))


class ActualizarPerfil(FormView):
    #esto hace que cuendo se acceda a la clase se requiera de un login, de lo contrario habria que ponerlo en cada metodo
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ActualizarPerfil, self).dispatch(*args, **kwargs)

    
    def get(self, request): 
        page_title = 'Perfil'
        page_sub_title= 'Actualizar Perfil'        
        form = PerfilForm(instance=request.user.perfil)
        return render_to_response('usuario/actualizarPerfil.html', locals(),context_instance=RequestContext(request))
    
    
    def post(self,request, *args,**kwargs):
        page_title = 'Perfil'
        page_sub_title= 'Actualizar Perfil'
        #obtener nombres, appellidos y Email ya q no son parte del modelo pero vienen en el post
        nombres= request.POST['nombres']
        apellidos= request.POST['apellidos']
        email= request.POST['email']
        #inicializar el dormulario con con el perfil del usuario y asignar los datos del post
        form = PerfilForm(request.POST,request.FILES,instance=Perfil.objects.get(usuario=request.user))
        if form.is_valid():
            form.save()
            usuario=request.user
            usuario.first_name=nombres
            usuario.last_name=apellidos
            usuario.email=email
            usuario.save()
            return  HttpResponseRedirect(reverse_lazy('perfil'))
        else:
            #perfil = get_object_or_404(Perfil, usuario=request.user)
            return render_to_response('usuario/actualizarPerfil.html', locals(),context_instance=RequestContext(request))


class Changepassword (FormView):
    @method_decorator(login_required)
    def get(self, request): 
        page_title = 'Perfil'
        page_sub_title= 'Cambio de clave'
       # perfil = get_object_or_404(Perfil, usuario=request.user)
        form = PasswordChangeForm(user=request.user)
        return render_to_response('usuario/CambiarClave.html', locals(),context_instance=RequestContext(request))   
    
    @method_decorator(login_required)
    def post(self, request):    
        form = PasswordChangeForm(user=request.user,data=request.POST)
        if form.is_valid():
            form.save()
            return  HttpResponseRedirect(reverse_lazy('perfil'))
        else:
            page_title = 'Perfil'
            page_sub_title= 'Cambio de <clave></clave>'
           # perfil = get_object_or_404(Perfil, usuario=request.user)
            return render_to_response('usuario/CambiarClave.html', locals(),context_instance=RequestContext(request))   

templates/usuario/CambiarClave.html
{% extends "base.html" %}


{% block main_content %}
	
<dl class="sub-nav ">
	<dt>submenu:</dt>
	<dd><a href="{% url 'perfil' %}"><i class='fi-folder'></i> Perfil</a></dd>
</dl>
<div class="panel">
	<label>Una vez que todos los datos sean validados correctamente, seras redirigido a tu perfil</label>
</div>

	<form method='POST' action="" data-abide>
		{% csrf_token %}
		<div class="row">			
			<div class="medium-6 columns">
				<label for="id_old_password">{{form.old_password.label}}</label>
				<input id='id_old_password' type="password" name='old_password' required placeholder='Contraseña antigua'>
				<small class="error">Este campo es requerido</small>
				{% if form.old_password.errors %}
					{% for  error in form.old_password.errors %}
						<div data-alert class="alert-box warning ">
						  {{error}}	
						  <a href="#" class="close">&times;</a>
						</div>
					{% endfor %}						
				{% endif %}			
			</div>
		</div>	
		<div class="row">
			<div class="medium-6 columns">
				<label for="id_new_password1">{{form.new_password1.label}}</label>
				<input id='id_new_password1' type="password" name='new_password1' required placeholder='Nueva Contraseña'>
				<small class="error">Este campo es requerido</small>
				{% if form.new_password1.errors %}
					{% for  error in form.new_password1.errors %}
						<div data-alert class="alert-box warning ">
						  {{error}}	
						  <a href="#" class="close">&times;</a>
						</div>
					{% endfor %}						
				{% endif %}	
			</div>
			<div class="medium-6 columns">
				<label for="id_new_password2">{{form.new_password2.label}}</label>
				<input id='id_new_password2' type="password" name='new_password2' required placeholder='Confirme la Nueva Contraseña' data-equalto="id_new_password1">
				<small class="error">Este campo es requerido y debe coincidir con la nueva contraseña</small>
				{% if form.new_password2.errors %}
					{% for  error in form.new_password2.errors %}
						<div data-alert class="alert-box warning ">
						  {{error}}	
						  <a href="#" class="close">&times;</a>
						</div>
					{% endfor %}						
				{% endif %}	
			</div>
			<div class="medium-4 columns">
			</div>
		</div>
		<button class="button small " data-hint="Seguidos" type="submit">
		  <i class="fi-save"></i> Guardar Cambios
		</button>
	</form>
	
	
{% endblock main_content %}

templates/usuario/actualizarPerfil.html
{% extends "base.html" %}

{% block statics %}
	<link rel="stylesheet" href="{{STATIC_URL}}css/jquery-ui.min.css">
	<link rel="stylesheet" href="{{STATIC_URL}}css/jquery.datetimepicker.css">
	<link rel="stylesheet" href="{{STATIC_URL}}css/jquery.flipcountdown.css">
	
	<script src='{{STATIC_URL}}js/vendor/jquery/jquery.js'></script>
	<script src='{{STATIC_URL}}js/vendor/jquery-ui.min.js'></script>
	<script src='{{STATIC_URL}}js/vendor/jquery.datetimepicker.js'></script>
	<script src='{{STATIC_URL}}js/vendor/jquery.flipcountdown.js'></script>

   <script>
  	$(document).ready(function(){
  		$("#id_fecha_nacimiento").datetimepicker({
	   		lang:'es',
	   		format:'d/m/Y H:i',
	   		startDate:'+1971/01/01'
	    });
  		//$('#retroclockbox1').flipcountdown({
  			//tzoneOffset:6,
  		//	am:true
  		//});
  	});  
  </script>
{% endblock statics %}

{% block main_content %}

	<dl class="sub-nav ">
		<dt>submenu:</dt>
		<dd><a href="{% url 'perfil' %}"><i class='fi-folder'></i> Perfil</a></dd>
	</dl>
	{% if  form.fecha_nacimiento.errors %}
		<div data-alert class="alert-box warning radius">
			{{form.fecha_nacimiento.errors}}
			<a href="#" class="close">&times;</a>
		</div>
	{% endif %}


<form method='POST' enctype='multipart/form-data'>
	{% csrf_token %}

	<div class="row">
		
		<div class="detalleperfil medium-9 columns text-left ">
			<h6 class='colorAzulOscuro2 detalleperfil txtlineBottonBluenice'> 
				<i class='fi-burst'></i> Informacion de Perfil
			</h6>	
			<div class="row">				
				<div class="small-12 columns">
					<div class="row">
						<div class="medium-6 columns">
							{{form.as_p}}	
						</div>
						<div class="medium-6 columns">
							<div class="row">
								<div class="small-12 columns ">
									<label for="">Nombres</label>
									<input type="text" placeholder='Nombres' name='nombres' value='{{ user.first_name }}'>
								</div>
							</div>
							<div class="row">
								<div class="small-12 columns ">
									<label for="">Apellidos</label>
									<input type="text" placeholder='Apellidos' name='apellidos' value='{{ user.last_name }}'>
								</div>
							</div>
							<div class="row">
								<div class="small-12 columns ">
									<label for="">E-mail</label>
									<input type="text" placeholder='E-Mail' name='email' value='{{ user.email }}'>
								</div>
							</div>
						</div>
					</div>
											
					
					{% comment %}
					{% endcomment %}
				
				</div>
			</div>
			<br>
		
			<button class="button small " data-hint="Seguidos" type="submit">
			  <i class="fi-save"></i> Guardar Cambios
			</button>
		</div>
		

	</div>
	
	<br>
</form>
	
{% endblock main_content %}

templates/usuario/login.html
	<form class="custom loginfrm" method="POST">
				 {% csrf_token %}
				 {% if form.non_field_errors %}				 	
				 	<div data-alert class="alert-box warning radius">
					  Por favor ingrese un nombre de usuario y clave correctas
					  <audio src="{{MEDIA_URL}}audio/dubstep_alert.mp3" autoplay></audio>
					  <a href="#" class="close">&times;</a>
					</div>	
				 {% endif %}

				<div class="panel radius">
					<h5 class="loginTitle">Inicia Sesion <i class="fi-shield"></i> </h5>				    
				     <div class="row collapse">
					    <div class="small-3 large-2 columns">
					      <span class="prefix"><i class="fi-torsos-male-female"></i>  </span>
					    </div>
					    <div class="small-9 large-10 columns">
					      <input type="text" name="username" placeholder="Usuario" required>
					    </div>
					</div> 
					<div class="row collapse">
					    <div class="small-3 large-2 columns">
					      <span class="prefix"><i class="fi-lock"></i>  </span>
					    </div>
					    <div class="small-9 large-10 columns">
					      <input type="password" name="password" placeholder="Clave" required>
					    </div>
					</div>
					<button class="button small large-12" data-hint="Seguidos" type="submit">
						  <i class="fi-key"></i> Indentificame
					</button>
				</div>
	</form>

templates/usuario/perfil.html
{% extends "base.html" %}

{% block main_content %}


	<div class="row">
		<div class="medium-3 columns text-right">
			<img src="{{MEDIA_URL}}{{ user.perfil.foto}}" alt="" >			
			<span class="label large-12  success">
				{% if  user.first_name  %}
					{{  user.first_name }} {{  user.last_name }}
				{% else %}
					No especificado
				{% endif %}	
				 
			</span> 
		</div>
		<div class="detalleperfil medium-9 columns text-left ">

			<dl class="sub-nav ">
				<dt>Opciones:</dt>
				<dd class="sn "><a href="{% url 'actualizar_clave' %}">
					<i class='fi-lock'></i> Cambiar mi clave</a>
				</dd>
				<dd class="sn "><a href="{% url 'actualizar_perfil' %}">
					<i class='fi-list-bullet'></i> Cambiar mis datos</a>
				</dd>
			</dl>

			<h6 class='colorAzulOscuro2 detalleperfil txtlineBottonBluenice'> 
				<i class='fi-burst'></i> Informacion Basica
			</h6>	
			<div class="row">
				<div class="small-3 columns ">
					<span class="label  large-12 text-right" style='font-weight: bold'>
						Usuario: <i class='fi-torso'></i>
					</span><br>
					<span class="label  large-12 text-right" style='font-weight: bold'>
						Acceso: <i class='fi-clock'></i>
					</span><br>
					<span class="label  large-12 text-right" style='font-weight: bold'>
						Onomastico: <i class='fi-crown'></i>
					</span> <br>
					<span class="label  large-12 text-right" style='font-weight: bold'>
						Cargo: <i class='fi-torso-business'></i>
					</span> <br>
				</div>
				<div class="small-9 columns">
					
					<div class="row">
						<div class="small-12 columns ">
							<span class="label  large-12 text-left" >								
								{{user.username}}									 
							</span>
						</div>
					</div>
					<div class="row">
						<div class="small-12 columns ">
							<span class="label  large-12 text-left" >								
								Hace {{ user.last_login | timesince}}
							</span>
						</div>
					</div>
					<div class="row">
						<div class="small-12 columns ">
							<span class="label  large-12 text-left" >
								{% if  user.perfil.fecha_nacimiento %}
									{{ user.perfil.fecha_nacimiento|date:'d - M - Y'}} 
									
								{% else %}
									No especificado
								{% endif %}								 
							</span>
						</div>
					</div>
					<div class="row">
						<div class="small-12 columns ">
							<span class="label  large-12 text-left" >
								{% if  user.perfil.cargo %}
									{{ user.perfil.cargo}} 
								{% else %}
									No especificado
								{% endif %}								 
							</span>
						</div>
					</div>
				
				</div>
			</div>
			<br>

			<h6 class='colorAzulOscuro2 detalleperfil txtlineBottonBluenice'> 
				<i class='fi-burst'></i> Informacion de Contacto
			</h6>	
			<div class="row">
				<div class="small-3 columns ">
					<div class="row">
						<div class="small-12 columns ">
							<span class="label  large-12 text-right" style='font-weight: bold'>
								E-Mail: <i class='fi-mail'></i>
							</span>
						</div>
					</div>
					<div class="row">
						<div class="small-12 columns ">
							<span class="label  large-12 text-right" style='font-weight: bold'>
								Telefono: <i class='fi-telephone'></i>
							</span>
						</div>
					</div>
				</div>
				<div class="small-9 columns">
					<div class="row">
						<div class="small-12 columns ">
							<span class="label  large-12 text-left" >
								{% if  user.email %}
									{{ user.email }} 
								{% else %}
									No especificado
								{% endif %}								 
							</span>
						</div>
					</div>
					<div class="row">
						<div class="small-12 columns ">
							<span class="label  large-12 text-left" >								
								{% if   user.perfil.telefono  %}
									{{ user.perfil.telefono }}  
								{% else %}
									No especificado
								{% endif %}
							</span>
						</div>
					</div>
					
				</div>
			</div>
		
		</div>
	</div>
	<br>

	
{% endblock main_content %}