eaai/urls.py
from django.conf.urls import patterns, include, url
from eaai import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from bitacora.views import CategoryViewSet, UserViewSet
from rest_framework import routers
#from horario.views import saveMachinereboots
router = routers.DefaultRouter()
router.register(r'categorias', CategoryViewSet)
router.register(r'usuarios', UserViewSet)
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'api/', include(router.urls)),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
    	{ 'document_root' : settings.MEDIA_ROOT  }),

    url(r'^bitacora/', include('bitacora.urls')),
    url(r'^sistemas/', include('sistemas.urls')),
    url(r'^dispositivos/', include('dispositivos.urls')),
    
    url(r'^horario/', include('horario.urls')),
    url(r'^gestion/', include('gestion.urls')),

    url(r'^', include('usuario.urls')),
    url(r'^select2/', include('django_select2.urls')),

)

sistemas/urls.py
from django.conf.urls import patterns, include, url
from .views import *
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',
    # Examples:
    #url(r'^notas/', 'bitacora.views.home', name='home'),
   # url(r'^notas/', index.as_view(), name='home'),
    
	#url(r'api-auth/'), include('rest_framework.urls',namespace='rest_framework')),
    #CATEGORIA
    url(r'^$', login_required(ListarSistemas.as_view()), name='list_sistemas'),
    url(r'^por-categoria/(\d+)/', login_required(FiltrarSistemas_X_Categoria.as_view()), name='filter_sistemas'),
    url(r'^(\d+)/', login_required(DetalleSistema.as_view()), name='detail_sistema'),
    url(r'^categorias/', login_required(ListarCategorias.as_view()), name='list_categorias'),
   #url(r'^sistemas/', ListarCategoria.as_view(), name='list_categoria'),
    # url(r'^eaai/', include('eaai.foo.urls')),

)

sistemas/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
#Categoria en las que se pueden agrupar los sitemas o dispositivos hardware o software
class Categoria(models.Model):
    name = models.CharField('Nombre',max_length=50,unique=True)
    description = models.TextField('Descripcion',max_length=120, help_text='Descripcion breve sobre la categoria')
    imagen =  models.ImageField( upload_to='sistemas/categorias',null=True, default= 'sistemas/categorias/default.png',help_text='Campo Opcional')
    is_active = models.BooleanField('Activo',default=True)
    created_at = models.DateTimeField(auto_now_add=True,verbose_name='creado el')
    updated_at = models.DateTimeField(auto_now=True,verbose_name='actualizado el')
    user = models.ForeignKey(User)

    class Meta:
        #db_table = 'categories'
        ordering = ['-created_at']
        verbose_name_plural = 'Categorias'
        verbose_name = 'Categoria'

    def __unicode__(self):
        return self.name

    def creado_por(self):
        return "%s %s" % (self.user.first_name, self.user.last_name,)



#Ubicacion fisica en donde se encuentran los sistemas o subsistemas
class Ubicacion(models.Model):
    name = models.CharField('Nombre',max_length=50,unique=True)
    description = models.TextField('Descripcion',max_length=120, help_text='Descripcion breve sobre la ubicacion')
    is_active = models.BooleanField('Activo',default=True)
    created_at = models.DateTimeField(auto_now_add=True,verbose_name='creado el')
    updated_at = models.DateTimeField(auto_now=True,verbose_name='actualizado el')
    user = models.ForeignKey(User,
         verbose_name='Creado por',)
    #parent = models.ForeignKey('self',
       # verbose_name='Ubicacion padre',null=True, blank=True)

    class Meta:
        #db_table = 'categories'
        ordering = ['-created_at']
        verbose_name_plural = 'Ubicaciones'
        verbose_name = 'Ubicacion'

    def __unicode__(self):
        return self.name
    
    def creado_por(self):
        return "%s %s" % (self.user.first_name, self.user.last_name,)


 #Sistemas que se usan en EAAI
class Sistema(models.Model):
    SYS_TYPE_CHOICES = (
        ('SW', 'SOFTWARE'),
        ('HW', 'HARDWARE'),
        ('OTRO', 'OTRO'),
    )
    name = models.CharField('Nombre',max_length=50, )
    short_name=models.CharField('Nombre Pos. (Siglas)',max_length=20,unique=True, default="", blank=False)
    description = models.TextField('Descripcion',max_length=120, help_text='Descripcion breve sobre el sistema')
    sys_type = models.CharField('Tipo de sistema',choices=SYS_TYPE_CHOICES, max_length=30)
    is_active = models.BooleanField('Activo',default=True)
    en_funcionamiento=models.BooleanField(default=True)
    ubication = models.ForeignKey(Ubicacion, verbose_name='Ubicacion')
    category = models.ForeignKey(Categoria, verbose_name='Categoria')
    imagen =  models.ImageField( upload_to='sistemas/sistemas', null=True, default= 'sistemas/sistemas/default.png',help_text='Campo Opcional')
    #parent = models.ForeignKey('self', verbose_name=u'Sistema Padre', null=True, blank=True,help_text='Campo Opcional')
    created_at = models.DateTimeField(auto_now_add=True,verbose_name='creado el')
    updated_at = models.DateTimeField(auto_now=True,verbose_name='actualizado el')
    user = models.ForeignKey(User, 
        verbose_name='Creado por',)
    
    class Meta:
         #db_table = 'categories'
        ordering = ['-created_at']
        verbose_name_plural = 'Sistemas'
        verbose_name = 'Sistema'

    def __unicode__(self):
        return self.short_name
    
    def creado_por(self):
        return "%s %s" % (self.user.first_name, self.user.last_name,)

sistemas/forms.py
from django.forms import ModelForm, TextInput, DateTimeInput
from django.contrib.admin import ModelAdmin
from sistemas.models import *
from suit.widgets import EnclosedInput, LinkedSelect
from suit.widgets import EnclosedInput
from django_select2.widgets import Select2MultipleWidget, Select2Widget


class SistemaForm(ModelForm):
	class Meta:
		model = Sistema
		exclude=('user',)
		widgets = {
            'ubication': Select2Widget(select2_options={
                'minimumResultsForSearch': 1,
                'closeOnSelect': True,
                'width':200
                }),
            'category': Select2Widget(select2_options={
                'minimumResultsForSearch': 1,
                'closeOnSelect': True,
                'width':200
                })
        }

class UbicacionForm(ModelForm):
    class Meta:
        model = Ubicacion
        exclude=('user',)

class CategoriaForm(ModelForm):
    class Meta:
        model = Categoria
        exclude=('user',)

sistemas/views.py
# Create your views here.
from django.views.generic import TemplateView, CreateView, ListView
from django.http import HttpResponse
from django.shortcuts import render_to_response,get_object_or_404
from django.template.context import RequestContext
from django.template.loader import get_template
from django.core.urlresolvers import reverse_lazy
from .models import *


class ListarCategorias(ListView):
	page_title = 'Sistemas'
	page_sub_title= 'Lista de Categorias' 
	template_name= 'sistemas/categoria/listCategoria.html'
	queryset= Categoria.objects.all().order_by('name', 'created_at')
	context_object_name= 'categorias'

class ListarSistemas(TemplateView):
	def get(self, request): 
		page_title = 'Sistemas'
		page_sub_title= 'Lista de Sistemas' 
		#categorias= Categoria.objects.all().order_by('name', 'created_at')
		sistemas= Sistema.objects.all().order_by('name', 'created_at')
		return render_to_response('sistemas/sistema/listSistema.html', locals(),context_instance=RequestContext(request))

class FiltrarSistemas_X_Categoria(TemplateView):
	def get(self, request,idcategoria): 
		print "filtr Sis"
		page_title = 'Sistemas'
		page_sub_title= 'Sistemas por categoria' 
		#categorias= Categoria.objects.all().order_by('name', 'created_at')
		cat= get_object_or_404(Categoria, pk=idcategoria)
		sistemas= Sistema.objects.filter(category=cat)
		return render_to_response('sistemas/sistema/listSistema.html', locals(),context_instance=RequestContext(request))

class DetalleSistema(TemplateView):
	def get(self, request,idSistema): 
		page_title = 'Sistemas'
		page_sub_title= 'Detalles' 
		#Categoria.objects.all().order_by('name', 'created_at')
		sistema= get_object_or_404(Sistema, pk=idSistema)
		detalle=True
		return render_to_response('sistemas/sistema/listSistema.html', locals(),context_instance=RequestContext(request))

templates/sistemas/sistema/listSistema.html
{% extends "base.html" %}




{% block left_content %}
<br>
<h5  class="subheader">Categorias</h5 >
		<ul class="side-nav">
		{% for categoria in categorias %}
			<li class="snav text-right">
				<a href="{% url 'filter_sistemas' categoria.pk %}">
					{{categoria.name}} <span class="badge ">&nbsp;{{ categoria.sistema_set.all.count }}&nbsp;</span>
				</a>
			</li>
		{% endfor %}
		</ul>
{% endblock left_content %}

{% block main_content %}

<dl class="sub-nav ">
	<dt>Opciones:</dt>
		<dd class="sn "><a href="{% url 'list_sistemas' %}">
			<i class='fi-list-bullet'></i> Todos</a>
		</dd>
		<dd class="sn "><a href="{% url 'list_categorias' %}">
			<i class='fi-list-bullet'></i> Categorias</a>
		</dd>
		<dd class="sn "><a href="/admin/sistemas/sistema/add/">
			<i class='fi-lightbulb'></i> Agregar nuevo</a>
		</dd>
</dl>

{% if  sistemas.count > 0  %}
	<ul class="small-block-grid-2 medium-block-grid-3 large-block-grid-4" data-equalizer> 

		{% for sistema in sistemas %}			
			<li>
				<div class="panel" data-equalizer-watch>				
					
					<h5 class="txtlineBottonBluenice subtitle2"> {{ sistema.short_name }} </h5>
					<small class=''>{{sistema.description}}</small><br>			
					<a href="{% url 'detail_sistema' sistema.pk %}" class="button tiny">Ver detalles</a>	
				</div>
			</li>
		{% endfor %}
	</ul>

{% elif sistema %}
	<div class="row">
		<div class="medium-2 column">	
			<img src="{{MEDIA_URL}}{{sistema.imagen}}" alt="slide 1" />
		</div>
		<div class="medium-10 column">			
				<div class="panel radius">	
					<h5 class="txtlineBottonBluenice subtitle2"> {{ sistema.name }} ( {{sistema.short_name}} )</h5>
					<p class='arsenal'>{{sistema.description}}</p>
					<div class="row">
						<div class="small-5 medium-2 column text-right">
							<label class='basic'>Tipo de sistema: </label>
							<label class='basic'>Estado: </label>
							<label class='basic'>Categoria: </label>
							<label class='basic'>Ubicacion: </label>
							<label class='basic'>Creado Por: </label>
							<label class='basic'>Creado el: </label>
						</div>
						<div class="small-5 medium-5 column end">
							<label class='arsenal'>
								{% if sistema.sys_type == "SW" %} Software {% else %}Hardware{% endif %}  <br>
								{% if sistema.en_funcionamiento %}En funcionamiento {% else %}Fuera de Servicio{% endif %} <br>
								{{sistema.category.name}} <br>
								{{sistema.ubication.name}} <br>
								{{sistema.user.username}} <br>
								{{sistema.created_at}} <br>
							</label>
						</div>
					</div>
				</div>
		</div>
	</div>

{% else %}
	<h4><i class='fi-trees'></i> No hay elementos que mostrar</h4>
{% endif %}

{% endblock main_content %}