dispositivos/urls.py
from django.conf.urls import patterns, include, url
from .views import *
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',    
	#url(r'api-auth/'), include('rest_framework.urls',namespace='rest_framework')),
    #CATEGORIA
    url(r'^listar$', login_required(listarDispositivos.as_view()), name='list_dispositivos'),
    url(r'^listar/componentes$', login_required(listarComponentesHW.as_view()), name='list_componentes'),
    url(r'^(\d+)/historial/nuevo/$', login_required(NuevoHistorialDispositivo.as_view()), name='nuevo_historial'),
    #url(r'^([-\w]+)/$', login_required(detallesDispositivos.as_view()), name='detalle_dispositivo'),
    url(r'^(?P<dis_pk>[-\w]+)/$', login_required(detallesDispositivos.as_view()), name='detalle_dispositivo'),
    #la url de arriva significa qye se recibe el parametro dis_pk que sea  1 o mas digitos (d para enteros y w para cualquier alfanumeroco)
   #url(r'^sistemas/', ListarCategoria.as_view(), name='list_categoria'),
    # url(r'^eaai/', include('eaai.foo.urls')),

)

eaai/urls.py
from django.conf.urls import patterns, include, url
from eaai import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from bitacora.views import CategoryViewSet, UserViewSet
from rest_framework import routers
#from horario.views import saveMachinereboots
router = routers.DefaultRouter()
router.register(r'categorias', CategoryViewSet)
router.register(r'usuarios', UserViewSet)
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'api/', include(router.urls)),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
    	{ 'document_root' : settings.MEDIA_ROOT  }),

    url(r'^bitacora/', include('bitacora.urls')),
    url(r'^sistemas/', include('sistemas.urls')),
    url(r'^dispositivos/', include('dispositivos.urls')),
    
    url(r'^horario/', include('horario.urls')),
    url(r'^gestion/', include('gestion.urls')),

    url(r'^', include('usuario.urls')),
    url(r'^select2/', include('django_select2.urls')),

)

dispositivos/models.py
from django.db import models
from django.contrib.auth. models import User
from sistemas.models import Ubicacion
from django.dispatch import receiver
import os

# Create your models here.

#1===============================================================================================
class Tipo_Dispositivo(models.Model):
    nombre= models.CharField(max_length=30,)
    activo= models.BooleanField("Activo",default=True)
    imagen =  models.ImageField( upload_to='dispositivos/tipo_dispositivo', null=True, default= 'dispositivos/tipo_dispositivo/default.png',help_text='Campo Opcional')
    actualizado = models.DateTimeField(auto_now=True,verbose_name='actualizado')
    creado = models.DateTimeField(auto_now_add=True,verbose_name='creado')
    usuario = models.ForeignKey(User, verbose_name='Creado por',)
    
    class Meta:
        verbose_name_plural = 'Tipos de Dispositivo'
        verbose_name = 'Tipo de Dispositivo'
        
    def __unicode__(self):
        return self.nombre

#2===============================================================================================
class Dispositivo(models.Model):
    TIPO_OS = (
        ('WINDOWS', 'Windows'),
        ('RHE', 'Red Hat'),
        ('CentOS', 'Cent OS'),
        ('Debian', 'Debian'),
        ('Solaris', 'Solaris'),
        ('CISCO', 'Cisco IOS'),
        ('OTRO', 'Otro'),
        ('N/A', 'No Aplica'),
    )
    TIPO_ESTADO = (
        ('FUNCIONAL', 'Funcional'),
        ('SEMIFUNCIONAL', 'Semifuncional'),
        ('FALLO', 'Fallo'),
    )
    nombre= models.CharField(max_length=30, unique=True)
    os = models.CharField('Sistema Operativo',choices=TIPO_OS, max_length=30,)
    marca = models.CharField("Marca", max_length=30,default="Sin Especificar")
    modelo = models.CharField("Modelo", max_length=30,default="Sin Especificar")
    serie = models.CharField("Numero de Serie", max_length=40, unique=True)
    inventario = models.CharField("Numero de Inventario", max_length=40, unique=True,null=True)
    ip=models.IPAddressField("Direccion IP", max_length=15,blank=True,default="0.0.0.0")
    mascara_red=models.CharField("Mascara IP", max_length=15,blank=True,default="N/A")
    descripcion = models.TextField('Descripcion',max_length=160, help_text='Descripcion del dispositivo',blank=True,default="Sin Especificar")
    ubicacion= models.CharField(max_length=30,help_text='Indica la ubicacion fisica')
    tipo=models.ForeignKey(Tipo_Dispositivo)
    estado=models.CharField(choices=TIPO_ESTADO, max_length=30,)
    activo= models.BooleanField("Activo",default=True)
    actualizado = models.DateTimeField(auto_now=True,verbose_name='actualizado')
    creado = models.DateTimeField(auto_now_add=True,verbose_name='creado')
    usuario = models.ForeignKey(User, verbose_name='Creado por',)

    class Meta:
        verbose_name_plural = 'Dispositivos'
        verbose_name = 'Dispositivo'
        
    def __unicode__(self):
        return self.nombre

#3===============================================================================================
class Tipo_Componente(models.Model):
    nombre= models.CharField(max_length=30,)
    activo= models.BooleanField("Activo",default=True)
    imagen =  models.ImageField( upload_to='dispositivos/componente', null=True, default= 'dispositivos/componente/default.png',help_text='Campo Opcional')
    actualizado = models.DateTimeField(auto_now=True,verbose_name='actualizado')
    creado = models.DateTimeField(auto_now_add=True,verbose_name='creado')
    usuario = models.ForeignKey(User, verbose_name='Creado por',)
    
    class Meta:
        verbose_name_plural = 'Tipos de Componente'
        verbose_name = 'Tipo de Componente'
        
    def __unicode__(self):
        return self.nombre
#4===============================================================================================
class Componente_hardware(models.Model):
    dispositivo= models.ForeignKey(Dispositivo,verbose_name='Instalado en',null=True)
    marca = models.CharField("Marca", max_length=30,default="Sin Especificar")
    modelo = models.CharField("Modelo", max_length=30,default="Sin Especificar")
    serie = models.CharField("Numero de Serie", max_length=40,unique=True)
    tipo =models.ForeignKey(Tipo_Componente)
    descripcion = models.TextField('Descripcion',max_length=160, help_text='Descripcion del componente',blank=True)
    activo= models.BooleanField("Activo",default=True)
    operando = models.BooleanField("En funcionemiento",default=True)
    actualizado = models.DateTimeField(auto_now=True,verbose_name='actualizado')
    creado = models.DateTimeField(auto_now_add=True,verbose_name='creado')
    usuario = models.ForeignKey(User, verbose_name='Creado por',)

    class Meta:
        verbose_name_plural = 'Componentes Hardware'
        verbose_name = 'Componente Hardware'
        
    def __unicode__(self):
        return self.serie

#5===============================================================================================
class Historial_equipo(models.Model):
    TIPO_ENTRADA = (
        ('MANTENIMIENTO', 'Mantenimiento'),
        ('FALLO', 'Fallo'),
    )
    TIPO_ESTADO = (
        ('FUNCIONAL', 'Funcional'),
        ('SEMIFUNCIONAL', 'Semifuncional'),
        ('FALLO', 'Fallo'),
    )
    dispositivo= models.ForeignKey(Dispositivo,)
    tipo_entrada = models.CharField("Entrada por",choices=TIPO_ENTRADA, max_length=30,)
    estado_antes=models.CharField(choices=TIPO_ESTADO, max_length=30,)
    descripcion = models.TextField(max_length=3000, help_text='Descripcion de trabajo',verbose_name='descripcion')
    estado_despues=models.CharField(choices=TIPO_ESTADO, max_length=30,)
    ubicacion_antes= models.CharField(max_length=40,)
    ubicacion_despues= models.CharField(max_length=40,)
    actualizado = models.DateTimeField(auto_now=True,verbose_name='actualizado')
    creado = models.DateTimeField(auto_now_add=True,verbose_name='creado')
    usuario = models.ForeignKey(User, verbose_name='Creado por',)

    class Meta:
        verbose_name_plural = 'Historial de dispositivos'
        verbose_name = 'Historial'
        ordering = ['-creado']
        
    def __unicode__(self):
        return self.tipo_entrada

dispositivos/forms.py
from django.forms import ModelForm, TextInput, DateTimeInput
from .models import  *
from suit.widgets import EnclosedInput, LinkedSelect
from suit.widgets import EnclosedInput
from suit_redactor.widgets import RedactorWidget
from django_select2.widgets import Select2MultipleWidget, Select2Widget



class Historial_Form(ModelForm):
    class Meta:
        model = Historial_equipo
        exclude=('usuario',)
        

class Dispositivo_Form(ModelForm):
    class Meta:
        model = Dispositivo
        exclude=('usuario',)

class Historial_equipo_AdminFRM(ModelForm):
    class Meta:
        model = Historial_equipo
        exclude=('usuario',)
        widgets = {
            'descripcion': RedactorWidget(editor_options={'lang': 'es'}),
            'dispositivo': Select2Widget(select2_options={
                'minimumResultsForSearch': 1,
                'closeOnSelect': True,
                'width':200
                }),
        }

class DispositivoAdminFRM(ModelForm):
    class Meta:
        model = Dispositivo
        exclude=('usuario',)
        widgets = {
            'descripcion': RedactorWidget(editor_options={'lang': 'es'}),
            'dispositivo': Select2Widget(select2_options={
                'minimumResultsForSearch': 1,
                'closeOnSelect': True,
                'width':200
                }),
        }

dispositivos/views.py
# Create your views here.
from .models import *
from .forms import *
from django.views.generic import TemplateView
from django.shortcuts import render_to_response, get_object_or_404
from django.template.context import RequestContext
from django.template.loader import get_template
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect

class listarDispositivos(TemplateView):
	def get(self, request): 
		page_title = 'Dispositivos'
		page_sub_title= 'Lista de Dispositivos' 
		devices= Dispositivo.objects.filter(activo=True).order_by('nombre',)
		return render_to_response('dispositivos/listDispositivos.html', locals(),context_instance=RequestContext(request))

class listarComponentesHW(TemplateView):
	def get(self, request): 
		page_title = 'Componentes'
		page_sub_title= 'Lista de Componentes' 
		componentes= Componente_hardware.objects.filter(activo=True).order_by('creado',)
		return render_to_response('dispositivos/componentes.html', locals(),context_instance=RequestContext(request))

class detallesDispositivos(TemplateView):
	def get(self, request,dis_pk): 
		page_title = 'Dispositivos'
		page_sub_title= 'Detalles de Dispositivo' 
		device =get_object_or_404(Dispositivo, serie=dis_pk,activo=True,)
		components =Componente_hardware.objects.filter(activo=True,dispositivo__pk=device.pk).order_by('creado',)
		return render_to_response('dispositivos/detalle.html', locals(),context_instance=RequestContext(request))

class NuevoHistorialDispositivo(TemplateView):
	def get(self, request,id_dev): 
		page_title = 'Dispositivos'
		page_sub_title= 'Historial de Dispositivo'
		device =get_object_or_404(Dispositivo, pk=id_dev,activo=True,)
		historia=Historial_equipo()
		historia.dispositivo=device
		historia.estado_antes=device.estado
		historia.ubicacion_antes=device.ubicacion
		form = Historial_Form(instance=historia)
		return render_to_response('dispositivos/nuevoHistorial.html', locals(),context_instance=RequestContext(request))

	def post(self,request,*args,**kwargs):
		form= Historial_Form(request.POST)
		if form.is_valid():
			hist=form.save(commit=False)
			hist.usuario=request.user
			device =get_object_or_404(Dispositivo, pk=hist.dispositivo.pk,activo=True,)
			device.estado=hist.estado_despues
			device.ubicacion=hist.ubicacion_despues
			device.save()
			hist.save()
			return  HttpResponseRedirect("/dispositivos/"+str(hist.dispositivo.pk))
		else:
			return render_to_response('dispositivos/nuevoHistorial.html', locals(),context_instance=RequestContext(request))			

templates/dispositivos/componentes.html
{% extends "base.html" %}

{% block statics %}
	<link rel="stylesheet" href="{{STATIC_URL}}css/jquery.dynatable.css">
	<script src='{{STATIC_URL}}js/vendor/jquery.dynatable.js'></script>
	<script>
		$(function() {
			$('#mitabla').dynatable({
				features: {
				    paginate: true,
				    sort: true,
				    pushState: true,
				    search: true,
				    recordCount: true,
				    perPageSelect: false
				  },
				  inputs: {
				    paginationPrev: 'Anterior',
				    paginationNext: 'Siguiente',
				    recordCountText: 'Mostrando ',
				    processingText: 'Processing...'
				  },
				   params: {
				    records: 'registros',
				  }
				});
	
		});
	</script>


{% endblock statics %}


{% block main_content %}
{% load i18n %} 

{% if  componentes %}	

<table id='mitabla' class="table table-bordered">
  <thead>
    <tr class='basic'>
      <th width="150px">No Serie</th>
      <th width="150px">Tipo</th>
      <th width="150px">Marca</th>
      <th width="150px">Modelo</th>
      <th width="100px">Estado</th>
      <th width="100px">Instalado en:</th>
      <th width="200px">Descripcion</th>
      
    </tr>
  </thead>
  <tbody>   

	{% for component in  componentes %}
		<tr >
		  <td > <a href="#" class='arsenal'><i class='fi-page-search'> {{component.serie}} </i></a></td>
		  <td>  
		  		<label class='arsenal'>{{component.tipo.nombre}}</label>
				<img src="{{MEDIA_URL}}{{component.tipo.imagen}}" style='width: 45px' alt="">				
		  </td>
		  <td>  <label class='arsenal'>{{component.marca}}</label></td>
		  <td>  <label class='arsenal'>{{component.modelo}}</label></td>
		  <td>  <label class='arsenal'>{{component.operando|yesno:"OK,Mal Estado"}}</label></td>
		  <td>  <label class='arsenal'>{{component.dispositivo}}</label></td>
		  <td>  <label class='arsenal'>{{component.descripcion}}</label></td>
	    </tr>	
	{% endfor %}
  </tbody>
</table>
{% else %}
	<h6>No hay elementos que mostrar</h6>
{% endif %}
{% endblock main_content %}

templates/dispositivos/detalle.html
{% extends "base.html" %}

{% block statics %}

<link rel="stylesheet" href="{{STATIC_URL}}css/jquery-ui.min.css">
<script src='{{STATIC_URL}}js/vendor/jquery/jquery.js'></script>
<script src='{{STATIC_URL}}js/vendor/jquery-ui.min.js'></script>
	<script>
		  $(function() {
		    $( "#accordion" ).accordion();
		    $( "#tabs" ).tabs();
		    $(".det").click(function(event) {
				event.preventDefault()
				id=event.target.id;
				  	$( "#detalle_" + id).dialog( "open" );
			});
			$( ".detalleH" ).dialog({
			      modal: true,
			      autoOpen:false,
			      maxHeight: 600,
			      width: "90%",
			      position: { my: "center top", at: "center top", of: window },
			      show: {
			        effect: "clip",
			        duration: 1000
			      },
			      hide: {
			        effect: "slide",
			        duration: 1000
			      },
			      buttons: {
			        Ok: function() {
			          $( this ).dialog( "close" );
			        }
			      }
			    });	
		   
		  });
  	</script>
{% endblock statics %}

{% block main_content %}

	<div class="row">
		<div class="columns medium-2 text-center">
			 <label><strong>{{device.tipo.nombre}}</strong></label>
			<a class="th radius" href="../img/demos/demo2.png">
				<img src="{{MEDIA_URL}}{{device.tipo.imagen}}" style='width: 80px' alt="">
			</a>
		</div>
		<div class="columns medium-2 text-right">			
			<label style='font-weight: bold'> Sistema Operativo:</label> 
			<label style='font-weight: bold'>Marca:</label> 
			<label style='font-weight: bold'>Modelo: </label> 
			<label style='font-weight: bold'>Numero de serie: </label> 
			<label style='font-weight: bold'>Direccion IP: </label> 
			<label style='font-weight: bold'>Mascara de red: </label> 
		</div>
		<div class="columns medium-2">	
			<label class='arsenal'> {{device.os}}</label> 
			<label class='arsenal'> {{device.marca}}</label> 		
			<label class='arsenal'> {{device.modelo}}</label> 
			<label class='arsenal'> {{device.serie}}</label> 
			<label class='arsenal'> {{device.ip}}</label> 
			<label class='arsenal'> {{device.mascara_red}}</label> 
		</div>
		<div class="columns medium-2 text-right">			
			<label style='font-weight: bold'> Inventario:</label> 
			<label style='font-weight: bold'> Ubicacion:</label> 
			<label style='font-weight: bold'>Estado:</label> 
			<label style='font-weight: bold'>Creado el: </label> 
			<label style='font-weight: bold'>Actualizado: </label> 
			<label style='font-weight: bold'>Creado por: </label> 
		</div>
		<div class="columns medium-3 end">	
			<label class='arsenal'> {{device.inventario}}</label> 
			<label class='arsenal'> {{device.ubicacion}}</label> 
			<label class='arsenal'>				
				{% if device.estado == "FUNCIONAL" %}
					<img src="{{STATIC_URL}}img/ok.png" style='width: 25px' alt="">
				{% elif device.estado == "FALLO" %}
					<img src="{{STATIC_URL}}img/error.png" style='width: 25px' alt="">
				{% else %}
						<img src="{{STATIC_URL}}img/warning.png" style='width: 25px' alt="">
				{% endif %} 
				{{device.estado  }}
			</label> 		
			<label class='arsenal'> {{device.creado}}</label> 
			<label class='arsenal'> {{device.actualizado}}</label> 
			<label class='arsenal'> {{device.usuario.username}}</label> 
		</div>
	</div>
<div class="row">
	<div class="columns medium-12 ">
		<div id="tabs">
			  <ul>
			    <li class='basic'><a href="#tabs-1">Historial</a></li>
			    <li class='basic'><a href="#tabs-2">Componentes</a></li>
			    <li class='basic'><a href="#tabs-3">Descripcion</a></li>
			  </ul>
			  <div id="tabs-1">

				<a href="{% url 'nuevo_historial' device.id %}" style="font-size: 12px;color:white" class="button small radius ">
				  <i class="fi-plus"></i> Agregar Historial
				</a>
			   	
			   		{% if  device.historial_equipo_set.all.count > 0 %}	

					<table id='mitabla' class="table table-bordered">
						<caption class='subtitle'>Historial del dispositivo</caption>
					  <thead>
					    <tr class='basic'>
					      <th width="140px">Entrada por</th>
					      <th width="140px">Estado inicial</th>
					      <th width="150px">Estado final</th>       
					      <th width="160px">Ubicacion inicial</th> 
					      <th width="150px">Ubicacion final</th> 
					      <th width="120px">Usuario </th> 
					      <th width="150px">Fecha </th> 
					      <th width="120px">Opcion </th>     
					    </tr>
					  </thead>
					  <tbody>   

								{% for history in   device.historial_equipo_set.all %}
									<tr class='arsenal'>
								      <td> {{history.tipo_entrada}}</td>
								      <td>
								      		{% if history.estado_antes == "FUNCIONAL" %}
												<img src="{{STATIC_URL}}img/ok.png" style='width: 34px' alt="">
											{% elif history.estado_antes == "FALLO" %}
												<img src="{{STATIC_URL}}img/error.png" style='width: 34px' alt="">
											{% else %}
													<img src="{{STATIC_URL}}img/warning.png" style='width: 34px' alt="">
											{% endif %} 
								      </td>	
								      <td>
								      		{% if history.estado_despues == "FUNCIONAL" %}
												<img src="{{STATIC_URL}}img/ok.png" style='width: 34px' alt="">
											{% elif history.estado_despues == "FALLO" %}
												<img src="{{STATIC_URL}}img/error.png" style='width: 34px' alt="">
											{% else %}
													<img src="{{STATIC_URL}}img/warning.png" style='width: 34px' alt="">
											{% endif %} 
								      </td>	
								      <td>{{history.ubicacion_antes}} </td>
								      <td>{{history.ubicacion_despues}} </td>	
								      <td>
								      	{{history.usuario}} 
								      </td>
								      <td>
								      	{{history.creado |  date:"D, d-b-y "}} 
								      </td>
								      
								      <td>
								      	<label><a class='det' href="#" id='{{history.pk}}'> <i class='fi-zoom-in'></i> Ver</a></label>
								      		

											<div id="detalle_{{history.pk}}" title="Detalles" class="detalleH">
												<label class='arsenal'><strong>Tareas relizadas </strong></label>
								        	 	{{history.descripcion | safe}}
											</div>

								      		
								      </td>
								      
								    </tr>	
								{% endfor %}
							  </tbody>
							</table>
							{% else %}
								<h6 class='arsenal'>No existen entradas en el historial</h6>
							{% endif %}
			    
			  </div>
			  <div id="tabs-2">
			    <p>
			    	
			    	{% if  components.count > 0 %}	

					<table id='mitabla' class="table table-bordered">
					  <thead>
					    <tr>
					      <th width="160px">Tipo</th> 
					      <th width="150px">Serie</th>
					      <th width="150px">Marca</th>
					      <th width="150px">Modelo</th>       
					      <th width="100px">Estado</th>  
					      <th width="180px">Descripcion</th>  
					    </tr>
					  </thead>
					  <tbody>   

								{% for component in  components %}
									<tr>
									  <td> {{component.tipo}}</td>
								      <td> {{component.serie}}</td>
								      <td> {{component.marca}}</td>
								      <td> {{component.modelo}}</td>								      
								      <td> {{component.operando|yesno:"OK,Falla"}}</td>
								  		<td> {{component.descripcion}}</td>	
								    </tr>	
								{% endfor %}
							  </tbody>
							</table>
							{% else %}
								<h6 class='arsenal'>No existen componentes asociados</h6>
							{% endif %}
			    	
			    </p>
			  </div>
			  <div id="tabs-3">
			  	
			    <label class='arsenal'>{{device.descripcion}}</label>	
			    
			  </div>
		</div>
	</div>
</div>


{% endblock main_content %}

templates/dispositivos/listDispositivos.html
{% extends "base.html" %}

{% block statics %}
	<link rel="stylesheet" href="{{STATIC_URL}}css/jquery.dynatable.css">
	<script src='{{STATIC_URL}}js/vendor/jquery.dynatable.js'></script>
	<script>
		$(function() {
			$('#mitabla').dynatable({
				features: {
				    paginate: true,
				    sort: true,
				    pushState: true,
				    search: true,
				    recordCount: true,
				    perPageSelect: false
				  },
				  inputs: {
				    paginationPrev: 'Anterior',
				    paginationNext: 'Siguiente',
				    recordCountText: 'Mostrando ',
				    processingText: 'Processing...'
				  },
				   params: {
				    records: 'registros',
				  }
				});
	
		});
	</script>


{% endblock statics %}


{% block main_content %}
{% load i18n %} 

{% if  devices %}	

<table id='mitabla' class="table table-bordered">
  <thead>
    <tr class='basic'>
      <th width="150px">N&deg; Serie</th>
      <th width="150px">N&deg; Inventario</th>
      <th width="150px">Nombre</th>
      <th width="120px">Tipo</th>       
      <th width="100px">Estado </th> 
      <th width="150px">Modelo </th> 
      <th width="150px">Sistema </th>    
    </tr>
  </thead>
  <tbody>   

	{% for device in  devices %}
		<tr >
		  <td> <a class='arsenal' href="{% url 'detalle_dispositivo' device.serie %}"><i class='fi-page-search'> {{device.serie}} </i></a></td>
		  <td> <label class='arsenal'>{{device.inventario}} </label></td>
	      <td> <label class='arsenal'>{{device.nombre}} </label></td>
	      <td><label class='arsenal'>{{device.tipo.nombre}} </label></td>
	      <td >
	      		{% if device.estado == "FUNCIONAL" %}
					<img src="{{STATIC_URL}}img/ok.png" style='width: 34px' alt="">
				{% elif device.estado == "FALLO" %}
					<img src="{{STATIC_URL}}img/error.png" style='width: 34px' alt="">
				{% else %}
						<img src="{{STATIC_URL}}img/warning.png" style='width: 34px' alt="">
				{% endif %} 
	      </td>	
	      <td><label class='arsenal'>{{device.modelo}} </label></td>	
	      <td>
	      	<label class='arsenal'>{{device.os}} </label>
	      	{% if device.os != "OTRO" and device.os != "N/A" %}
				<a class="th radius" href="../img/demos/demo2.png">
					<img src="{{MEDIA_URL}}dispositivos/dispositivo/{{device.os}}.png" style='width: 30px' alt="">
				</a>
			{% endif %}
	      </td>
	    </tr>	
	{% endfor %}
  </tbody>
</table>
{% else %}
	<h6 class='arsenal'>No hay elementos que mostrar</h6>
{% endif %}
{% endblock main_content %}

templates/dispositivos/nuevoHistorial.html
{% extends "base.html" %}

{% block statics %}
	<link rel="stylesheet" href="{{STATIC_URL}}css/select2.css">
	<script src='{{STATIC_URL}}js/vendor/jquery/jquery.js'></script>
	<script src='{{STATIC_URL}}js/vendor/select2.min.js'></script>
	<script src='{{STATIC_URL}}js/vendor/select2_locale_es.js'></script>
	<script>
		$(document).ready(function() {
			 $("select").select2({
			 	  width: "resolve"
			 }); 
			  $("select").attr('required', 'true');
			  $("#id_descripcion").attr('required', 'true');
			  $("#id_ubicacion_antes").attr('required', 'true');
			  $("#id_ubicacion_despues").attr('required', 'true');

		});
	</script>
{% endblock statics %}

{% block main_content %}
	{{device}}
	<form method="POST">
		{% csrf_token %}
		<div class="row">
			<div class="columns medium-3">
				<label for="id_dispositivo">{{form.dispositivo.label}}:</label>
				{{form.dispositivo}}
				{{form.dispositivo.errors}}
			</div>
			<div class="columns medium-3 end">
				<label for="id_tipo_entrada">{{form.tipo_entrada.label}}:</label>
				{{form.tipo_entrada}}
				{{form.tipo_entrada.errors}}
			</div>
			<div class="columns medium-3">
				<label for="id_estado_antes">{{form.estado_antes.label}}:</label>
				{{form.estado_antes}}
				{{form.estado_antes.errors}}
			</div>
			<div class="columns medium-3 end">
				<label for="id_ubicacion_antes">{{form.ubicacion_antes.label}}:
				{{form.ubicacion_antes}}
				{{form.ubicacion_antes.errors}}
				</label>
			</div>
		</div>
		<div class="row">
			<div class="columns medium-8 end">
				<label for="id_descripcion">{{form.descripcion.label}}:
					{{form.descripcion}}
					{{form.descripcion.errors}}
				</label>
			</div>
		</div>
		<div class="row">
			<div class="columns medium-3">
				<label for="id_estado_despues">{{form.estado_despues.label}}:</label>
				{{form.estado_despues}}
				{{form.estado_despues.errors}}
			</div>
			<div class="columns medium-3 end">
				<label for="id_ubicacion_despues">{{form.ubicacion_despues.label}}:
				{{form.ubicacion_despues}}
				{{form.ubicacion_despues.errors}}
				</label>
			</div>
			<div class="columns medium-3 end">
				<button class="button small " data-hint="Seguidos" type="submit">
				  <i class="fi-save"></i> Guardar
				</button>
			</div>
		</div>
		
	</form>
{% endblock main_content %}